name: MainDeployCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v18.16.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: git config user.name github-actions[bot]
        && git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        && npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
